site_name: DataRescue Workflow
pages:
    - Home: index.md
    - Website Archiving:
      - Seeding: seeding.md
    - Archiving More Complex Datasets:
      - Researching: researching.md
      - Harvesting: harvesting.md
      - Checking/Bagging: bagging.md
      - Describing: describing.md
    - Event Organizing:
      - Before an Event: organizing/pre-event.md
      - After an Event: organizing/post-event.md
    - Additional Resources:
      - Archivers App FAQ: faq.md
theme: readthedocs
theme_dir: custom_theme
extra_css:
    - css/extra.css
